// AUTO-GENERATED by generate-phenotype-physics.rs - DO NOT EDIT

pub const N_AGENTS: usize = 100;
pub const GENE_LEN: usize = 10;
pub const HIDDEN_LEN: usize = 10;

pub const STATE_DIMS: usize = 5;
pub const STATE_VARS: [&str; 5] = [
    "pos_x",
    "pos_y",
    "vel_x",
    "vel_y",
    "size",
];

#[allow(dead_code)]
pub fn init_state(
    n_agents: usize,
    device: &candle_core::Device,
) -> candle_core::Result<candle_core::Tensor> {
    let init_pos_x = candle_core::Tensor::rand(-500f32, 500f32, (n_agents, 1), device)?;
    let init_pos_y = candle_core::Tensor::rand(-500f32, 500f32, (n_agents, 1), device)?;
    let init_vel_x = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_vel_y = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_size = candle_core::Tensor::rand(1f32, 10f32, (n_agents, 1), device)?;

    candle_core::Tensor::cat(&[
        &init_pos_x,
        &init_pos_y,
        &init_vel_x,
        &init_vel_y,
        &init_size,
    ], 1)
}

#[allow(dead_code)]
#[allow(unused_variables)]
pub fn update_dynamics(
    state: &candle_core::Tensor,
    p_physics: &candle_core::Tensor,
    p_attributes: &candle_core::Tensor,
) -> candle_core::Result<candle_core::Tensor> {
    // State variable decomposition
    let s_pos_x = state.narrow(1, 0, 1)?;
    let s_pos_y = state.narrow(1, 1, 1)?;
    let s_vel_x = state.narrow(1, 2, 1)?;
    let s_vel_y = state.narrow(1, 3, 1)?;
    let s_size = state.narrow(1, 4, 1)?;

    // Parameter decomposition
    let p_dummy_phys = p_physics.narrow(1, 0, 1)?;
    let p_dummy_attr = p_attributes.narrow(1, 0, 1)?;


    // Internal dynamics operations
    let temp_0 = candle_core::Tensor::new(&[0.1f32], state.device())?;
    let temp_1 = s_vel_x.broadcast_mul(&temp_0)?;
    let temp_2 = s_pos_x.broadcast_add(&temp_1)?;
    let pos_x = temp_2;
    let temp_3 = s_vel_y.broadcast_mul(&temp_0)?;
    let temp_4 = s_pos_y.broadcast_add(&temp_3)?;
    let pos_y = temp_4;
    let vel_x = s_vel_x;
    let vel_y = s_vel_y;
    let temp_5 = candle_core::Tensor::new(&[0f32], state.device())?;
    let temp_6 = {
                    let lhs = s_pos_x.broadcast_as((state.dim(0)?, 1))?;
                    let rhs = temp_5.broadcast_as((state.dim(0)?, 1))?;
                    lhs.gt(&rhs)?.to_dtype(candle_core::DType::F32)?
                };
    let temp_7 = candle_core::Tensor::new(&[1f32], state.device())?;
    let temp_8 = temp_6.broadcast_mul(&temp_7.broadcast_sub(&temp_5)?)?.broadcast_add(&temp_5)?;
    let temp_9 = p_dummy_phys.broadcast_mul(&temp_5)?;
    let temp_10 = p_dummy_attr.broadcast_mul(&temp_5)?;
    let temp_11 = temp_9.broadcast_add(&temp_10)?;
    let temp_12 = temp_8.broadcast_add(&temp_11)?;
    let size = temp_12;

    // Boundary conditions
    // torus wrap: pos_x in [-500.000000,500.000000]
    let pos_x = {
        let min = candle_core::Tensor::new(&[-500.000000f32], state.device())?;
        let width = candle_core::Tensor::new(&[1000.000000f32], state.device())?;
        let norm = pos_x.broadcast_sub(&min)?;
        let div = norm.broadcast_div(&width)?;
        let floor = div.floor()?;
        let term = floor.broadcast_mul(&width)?;
        let rem = norm.broadcast_sub(&term)?;
        rem.broadcast_add(&min)?
    };
    // torus wrap: pos_y in [-500.000000,500.000000]
    let pos_y = {
        let min = candle_core::Tensor::new(&[-500.000000f32], state.device())?;
        let width = candle_core::Tensor::new(&[1000.000000f32], state.device())?;
        let norm = pos_y.broadcast_sub(&min)?;
        let div = norm.broadcast_div(&width)?;
        let floor = div.floor()?;
        let term = floor.broadcast_mul(&width)?;
        let rem = norm.broadcast_sub(&term)?;
        rem.broadcast_add(&min)?
    };

    // Concatenate updated state
    let n_agents = state.dim(0)?;
    candle_core::Tensor::cat(&[
        &pos_x.broadcast_as((n_agents, 1))?,
        &pos_y.broadcast_as((n_agents, 1))?,
        &vel_x.broadcast_as((n_agents, 1))?,
        &vel_y.broadcast_as((n_agents, 1))?,
        &size.broadcast_as((n_agents, 1))?,
    ], 1)
}
