// AUTO-GENERATED by generate-phenotype-physics.rs - DO NOT EDIT

pub const N_AGENTS: usize = 10000;
pub const GENE_LEN: usize = 32;
pub const HIDDEN_LEN: usize = 64;

use crate::grid::{SpatialGrid, particles_to_grid, grid_to_particles};

pub const GRID_CONFIG: SpatialGrid = SpatialGrid {
    width: 80,
    height: 64,
    capacity: 8,
    cell_size: (128.000000, 125.000000),
};

pub const STATE_DIMS: usize = 5;
pub const STATE_VARS: [&str; 5] = [
    "pos_x",
    "pos_y",
    "vel_x",
    "vel_y",
    "size",
];

#[allow(dead_code)]
pub fn init_state(
    n_agents: usize,
    device: &candle_core::Device,
) -> candle_core::Result<candle_core::Tensor> {
    let init_pos_x = candle_core::Tensor::rand(-200f32, 200f32, (n_agents, 1), device)?;
    let init_pos_y = candle_core::Tensor::rand(-200f32, 200f32, (n_agents, 1), device)?;
    let init_vel_x = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_vel_y = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_size = candle_core::Tensor::rand(1f32, 10f32, (n_agents, 1), device)?;

    candle_core::Tensor::cat(&[
        &init_pos_x,
        &init_pos_y,
        &init_vel_x,
        &init_vel_y,
        &init_size,
    ], 1)
}

#[allow(dead_code)]
pub fn update_dynamics(
    state: &candle_core::Tensor,
    p_physics: &candle_core::Tensor,
    p_attributes: &candle_core::Tensor,
) -> candle_core::Result<candle_core::Tensor> {
    // State variable decomposition
    let s_pos_x = state.narrow(1, 0, 1)?;
    let s_pos_y = state.narrow(1, 1, 1)?;
    let s_vel_x = state.narrow(1, 2, 1)?;
    let s_vel_y = state.narrow(1, 3, 1)?;
    let s_size = state.narrow(1, 4, 1)?;

    // Parameter decomposition
    let p_grav_g = p_physics.narrow(1, 0, 1)?;
    let p_dummy_attr = p_attributes.narrow(1, 0, 1)?;

    #[allow(unused_assignments)]
    let mut temp_3_indices: candle_core::Tensor = candle_core::Tensor::zeros(1, candle_core::DType::U32, state.device())?;

    // Internal dynamics operations
    let temp_0 = s_pos_x.broadcast_add(&s_vel_x)?;
    let pos_x = temp_0;
    let temp_1 = s_pos_y.broadcast_add(&s_vel_y)?;
    let pos_y = temp_1;
    let temp_2 = candle_core::Tensor::cat(&[&s_pos_x, &s_pos_y, &s_vel_x, &s_vel_y, &s_size], 1)?;
    let temp_3 = {
                    let (grid, _mask, indices) = particles_to_grid(&s_pos_x, &s_pos_y, &temp_2, &GRID_CONFIG)?;
                    temp_3_indices = indices;
                    grid
                };
    let temp_4 = crate::grid::solve_gravity_stencil(&temp_3, 1)?;
    let temp_5 = grid_to_particles(&temp_4, &temp_3_indices)?;
    let temp_6 = temp_5.narrow(1, 2, 1)?;
    let temp_7 = candle_core::Tensor::new(&[0f32], state.device())?;
    let temp_8 = p_grav_g.broadcast_mul(&temp_7)?;
    let temp_9 = p_dummy_attr.broadcast_mul(&temp_7)?;
    let temp_10 = temp_8.broadcast_add(&temp_9)?;
    let temp_11 = temp_6.broadcast_add(&temp_10)?;
    let temp_12 = s_vel_x.broadcast_add(&temp_11)?;
    let vel_x = temp_12;
    let temp_13 = temp_5.narrow(1, 3, 1)?;
    let temp_14 = temp_13.broadcast_add(&temp_10)?;
    let temp_15 = s_vel_y.broadcast_add(&temp_14)?;
    let vel_y = temp_15;
    let size = s_size;

    // Boundary conditions
    // torus wrap: pos_x in [-5120.000000,5120.000000]
    let pos_x = {
        let min = candle_core::Tensor::new(&[-5120.000000f32], state.device())?;
        let width = candle_core::Tensor::new(&[10240.000000f32], state.device())?;
        let norm = pos_x.broadcast_sub(&min)?;
        let div = norm.broadcast_div(&width)?;
        let floor = div.floor()?;
        let term = floor.broadcast_mul(&width)?;
        let rem = norm.broadcast_sub(&term)?;
        rem.broadcast_add(&min)?
    };
    // torus wrap: pos_y in [-4000.000000,4000.000000]
    let pos_y = {
        let min = candle_core::Tensor::new(&[-4000.000000f32], state.device())?;
        let width = candle_core::Tensor::new(&[8000.000000f32], state.device())?;
        let norm = pos_y.broadcast_sub(&min)?;
        let div = norm.broadcast_div(&width)?;
        let floor = div.floor()?;
        let term = floor.broadcast_mul(&width)?;
        let rem = norm.broadcast_sub(&term)?;
        rem.broadcast_add(&min)?
    };

    // Concatenate updated state
    candle_core::Tensor::cat(&[
        &pos_x,
        &pos_y,
        &vel_x,
        &vel_y,
        &size,
    ], 1)
}
