// AUTO-GENERATED by generate-phenotype-physics.rs - DO NOT EDIT

pub const STATE_DIMS: usize = 5;
pub const STATE_VARS: [&str; 5] = [
    "pos_x",
    "pos_y",
    "vel_x",
    "vel_y",
    "size",
];

#[allow(dead_code)]
pub fn init_state(
    n_agents: usize,
    device: &candle_core::Device,
) -> candle_core::Result<candle_core::Tensor> {
    let init_pos_x = candle_core::Tensor::rand(-512f32, 512f32, (n_agents, 1), device)?;
    let init_pos_y = candle_core::Tensor::rand(-400f32, 400f32, (n_agents, 1), device)?;
    let init_vel_x = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_vel_y = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_size = candle_core::Tensor::rand(1f32, 3f32, (n_agents, 1), device)?;

    candle_core::Tensor::cat(&[
        &init_pos_x,
        &init_pos_y,
        &init_vel_x,
        &init_vel_y,
        &init_size,
    ], 1)
}

#[allow(dead_code)]
pub fn update_dynamics(
    state: &candle_core::Tensor,
    p_physics: &candle_core::Tensor,
    p_attributes: &candle_core::Tensor,
) -> candle_core::Result<candle_core::Tensor> {
    // State variable decomposition
    let s_pos_x = state.narrow(1, 0, 1)?;
    let s_pos_y = state.narrow(1, 1, 1)?;
    let s_vel_x = state.narrow(1, 2, 1)?;
    let s_vel_y = state.narrow(1, 3, 1)?;
    let s_size = state.narrow(1, 4, 1)?;

    // Parameter decomposition
    let p_grav_g = p_physics.narrow(1, 0, 1)?;
    let p_dummy_attr = p_attributes.narrow(1, 0, 1)?;

    // Internal dynamics operations
    let temp_0 = candle_core::Tensor::new(&[0.1f32], state.device())?;
    let temp_1 = s_vel_x.broadcast_mul(&temp_0)?;
    let temp_2 = s_pos_x.broadcast_add(&temp_1)?;
    let pos_x = temp_2;
    let temp_3 = s_vel_y.broadcast_mul(&temp_0)?;
    let temp_4 = s_pos_y.broadcast_add(&temp_3)?;
    let pos_y = temp_4;
    let temp_5 = candle_core::Tensor::new(&[100f32], state.device())?;
    let temp_6 = candle_core::Tensor::new(&[0f32], state.device())?;
    let temp_7 = p_grav_g.broadcast_mul(&temp_6)?;
    let temp_8 = p_dummy_attr.broadcast_mul(&temp_6)?;
    let temp_9 = temp_7.broadcast_add(&temp_8)?;
    let temp_10 = temp_5.broadcast_add(&temp_9)?;
    let temp_11 = s_size.transpose(0, 1)?;
    let temp_12 = s_pos_x.transpose(0, 1)?;
    let temp_13 = temp_12.broadcast_sub(&s_pos_x)?;
    let temp_14 = temp_11.broadcast_mul(&temp_13)?;
    let temp_15 = candle_core::Tensor::new(&[1f32], state.device())?;
    let temp_16 = temp_13.broadcast_mul(&temp_13)?;
    let temp_17 = s_pos_y.transpose(0, 1)?;
    let temp_18 = temp_17.broadcast_sub(&s_pos_y)?;
    let temp_19 = temp_18.broadcast_mul(&temp_18)?;
    let temp_20 = temp_16.broadcast_add(&temp_19)?;
    let temp_21 = candle_core::Tensor::new(&[0.0001f32], state.device())?;
    let temp_22 = temp_20.broadcast_add(&temp_21)?;
    let temp_23 = temp_22.sqrt()?;
    let temp_24 = temp_15.broadcast_div(&temp_23)?;
    let temp_25 = temp_24.broadcast_div(&temp_22)?;
    let temp_26 = temp_14.broadcast_mul(&temp_25)?;
    let temp_27 = temp_26.sum_keepdim(1)?;
    let temp_28 = temp_10.broadcast_mul(&temp_27)?;
    let temp_29 = temp_28.broadcast_mul(&temp_0)?;
    let temp_30 = s_vel_x.broadcast_add(&temp_29)?;
    let vel_x = temp_30;
    let temp_31 = temp_11.broadcast_mul(&temp_18)?;
    let temp_32 = temp_31.broadcast_mul(&temp_25)?;
    let temp_33 = temp_32.sum_keepdim(1)?;
    let temp_34 = temp_10.broadcast_mul(&temp_33)?;
    let temp_35 = temp_34.broadcast_mul(&temp_0)?;
    let temp_36 = s_vel_y.broadcast_add(&temp_35)?;
    let vel_y = temp_36;
    let size = s_size;

    // Concatenate updated state
    candle_core::Tensor::cat(&[
        &pos_x,
        &pos_y,
        &vel_x,
        &vel_y,
        &size,
    ], 1)
}
