// AUTO-GENERATED by generate-phenotype-physics.rs - DO NOT EDIT

pub const N_AGENTS: usize = 100;
pub const GENE_LEN: usize = 32;
pub const HIDDEN_LEN: usize = 64;

pub const STATE_DIMS: usize = 5;
pub const STATE_VARS: [&str; 5] = [
    "pos_x",
    "pos_y",
    "vel_x",
    "vel_y",
    "size",
];

#[allow(dead_code)]
pub fn init_state(
    n_agents: usize,
    device: &candle_core::Device,
) -> candle_core::Result<candle_core::Tensor> {
    let init_pos_x = candle_core::Tensor::rand(-170.66667f32, 170.66667f32, (n_agents, 1), device)?;
    let init_pos_y = candle_core::Tensor::rand(-133.33333f32, 133.33333f32, (n_agents, 1), device)?;
    let init_vel_x = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_vel_y = candle_core::Tensor::randn(0f32, 10f32, (n_agents, 1), device)?;
    let init_size = candle_core::Tensor::rand(1f32, 1.1f32, (n_agents, 1), device)?;

    candle_core::Tensor::cat(&[
        &init_pos_x,
        &init_pos_y,
        &init_vel_x,
        &init_vel_y,
        &init_size,
    ], 1)
}

#[allow(dead_code)]
pub fn update_dynamics(
    state: &candle_core::Tensor,
    p_physics: &candle_core::Tensor,
    p_attributes: &candle_core::Tensor,
) -> candle_core::Result<candle_core::Tensor> {
    // State variable decomposition
    let s_pos_x = state.narrow(1, 0, 1)?;
    let s_pos_y = state.narrow(1, 1, 1)?;
    let s_vel_x = state.narrow(1, 2, 1)?;
    let s_vel_y = state.narrow(1, 3, 1)?;
    let s_size = state.narrow(1, 4, 1)?;

    // Parameter decomposition
    let p_grav_g = p_physics.narrow(1, 0, 1)?;
    let p_dummy_attr = p_attributes.narrow(1, 0, 1)?;

    // Internal dynamics operations
    let temp_0 = s_pos_x.broadcast_add(&s_vel_x)?;
    let pos_x = temp_0;
    let temp_1 = s_pos_y.broadcast_add(&s_vel_y)?;
    let pos_y = temp_1;
    let temp_2 = candle_core::Tensor::new(&[10f32], state.device())?;
    let temp_3 = candle_core::Tensor::new(&[0f32], state.device())?;
    let temp_4 = p_grav_g.broadcast_mul(&temp_3)?;
    let temp_5 = p_dummy_attr.broadcast_mul(&temp_3)?;
    let temp_6 = temp_4.broadcast_add(&temp_5)?;
    let temp_7 = temp_2.broadcast_add(&temp_6)?;
    let temp_8 = s_size.transpose(0, 1)?;
    let temp_9 = s_pos_x.transpose(0, 1)?;
    let temp_10 = temp_9.broadcast_sub(&s_pos_x)?;
    let temp_11 = temp_8.broadcast_mul(&temp_10)?;
    let temp_12 = candle_core::Tensor::new(&[1f32], state.device())?;
    let temp_13 = temp_10.broadcast_mul(&temp_10)?;
    let temp_14 = s_pos_y.transpose(0, 1)?;
    let temp_15 = temp_14.broadcast_sub(&s_pos_y)?;
    let temp_16 = temp_15.broadcast_mul(&temp_15)?;
    let temp_17 = temp_13.broadcast_add(&temp_16)?;
    let temp_18 = candle_core::Tensor::new(&[0.0001f32], state.device())?;
    let temp_19 = temp_17.broadcast_add(&temp_18)?;
    let temp_20 = temp_12.broadcast_div(&temp_19)?;
    let temp_21 = temp_11.broadcast_mul(&temp_20)?;
    let temp_22 = temp_21.sum_keepdim(1)?;
    let temp_23 = temp_7.broadcast_mul(&temp_22)?;
    let temp_24 = s_vel_x.broadcast_add(&temp_23)?;
    let vel_x = temp_24;
    let temp_25 = temp_8.broadcast_mul(&temp_15)?;
    let temp_26 = temp_25.broadcast_mul(&temp_20)?;
    let temp_27 = temp_26.sum_keepdim(1)?;
    let temp_28 = temp_7.broadcast_mul(&temp_27)?;
    let temp_29 = s_vel_y.broadcast_add(&temp_28)?;
    let vel_y = temp_29;
    let size = s_size;

    // Concatenate updated state
    candle_core::Tensor::cat(&[
        &pos_x,
        &pos_y,
        &vel_x,
        &vel_y,
        &size,
    ], 1)
}
